#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PROJECTS_FILE="$SCRIPT_DIR/config/projects.env"
WEB_SRC_DIR="$SCRIPT_DIR/web"
WEB_ROOT="/var/www/vps-projects"

NGINX_CONF="/etc/nginx/sites-available/vps-projects"
NGINX_LINK="/etc/nginx/sites-enabled/vps-projects"
NGINX_DEFAULT_LINK="/etc/nginx/sites-enabled/default"
NGINX_DEFAULT_CONF="/etc/nginx/conf.d/default.conf"
NGINX_DIR="/etc/nginx"
SITES_ENABLED_DIR="/etc/nginx/sites-enabled"
CONF_D_DIR="/etc/nginx/conf.d"
DISABLED_DIR="/etc/nginx/disabled-by-vps-iac"

BASE_DOMAIN="${BASE_DOMAIN:-amjad.cloud}"
CERTBOT_EMAIL="amgad.wr.1@gmail.com"

echo "🚀 Setting up Nginx reverse proxy..."
echo "   Base domain: $BASE_DOMAIN"

if [ "${EUID:-0}" -eq 0 ]; then
  SUDO=""
else
  SUDO="sudo"
fi

if [ ! -f "$PROJECTS_FILE" ]; then
  echo "❌ Projects file not found: $PROJECTS_FILE"
  exit 1
fi

if [ ! -d "$WEB_SRC_DIR" ]; then
  echo "❌ Web directory not found: $WEB_SRC_DIR"
  exit 1
fi

echo "📦 Syncing static assets..."
$SUDO mkdir -p "$WEB_ROOT"
$SUDO cp -a "$WEB_SRC_DIR/." "$WEB_ROOT/"

OUT_CONF="$SCRIPT_DIR/projects.conf"
TMP_CONF="$(mktemp)"

# ==============================================================================
# 1. Generate Nginx Configuration
# ==============================================================================

# --- Path-based server + base domain dashboard ---
# server_name _ amjad.cloud  =>  amjad.cloud/ serves the dashboard,
#                              IP/ falls back here too (default_server),
#                              /portfolio/ etc. are proxied below.
cat > "$TMP_CONF" <<EOF
# Auto-generated by setup_nginx.sh
# WARNING: This file is overwritten on each run.
# Certbot SSL sections are re-applied automatically at the end of the script.

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _ $BASE_DOMAIN;

    root $WEB_ROOT;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }

EOF

DOMAINS=("$BASE_DOMAIN")

while IFS="|" read -r name path port; do
  name="${name#"${name%%[![:space:]]*}"}"
  name="${name%"${name##*[![:space:]]}"}"
  path="${path#"${path%%[![:space:]]*}"}"
  path="${path%"${path##*[![:space:]]}"}"
  port="${port#"${port%%[![:space:]]*}"}"
  port="${port%"${port##*[![:space:]]}"}"

  if [ -z "$name" ] || [[ "$name" == \#* ]]; then
    continue
  fi

  if [ -z "$path" ] || [ -z "$port" ]; then
    echo "⚠️  Skipping invalid line: name='$name' path='$path' port='$port'"
    continue
  fi

  if [[ "$path" != /* ]]; then
    echo "⚠️  Skipping invalid path (must start with '/'): $path"
    continue
  fi

  echo "📦 Adding $name → $path → $port"

  cat >> "$TMP_CONF" <<EOF
    location = $path {
        return 301 $path/;
    }

    location ^~ $path/ {
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Prefix $path;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_pass http://127.0.0.1:$port/;
    }

EOF

  DOMAINS+=("$name.$BASE_DOMAIN")
done < "$PROJECTS_FILE"

echo "}" >> "$TMP_CONF"

# --- Subdomain server blocks ---
while IFS="|" read -r name path port; do
  name="${name#"${name%%[![:space:]]*}"}"
  name="${name%"${name##*[![:space:]]}"}"
  path="${path#"${path%%[![:space:]]*}"}"
  path="${path%"${path##*[![:space:]]}"}"
  port="${port#"${port%%[![:space:]]*}"}"
  port="${port%"${port##*[![:space:]]}"}"

  if [ -z "$name" ] || [[ "$name" == \#* ]]; then
    continue
  fi

  if [ -z "$path" ] || [ -z "$port" ]; then
    continue
  fi

  if [[ "$path" != /* ]]; then
    continue
  fi

  SUBDOMAIN="$name.$BASE_DOMAIN"

  cat >> "$TMP_CONF" <<EOF

# Subdomain: $SUBDOMAIN
server {
    listen 80;
    listen [::]:80;
    server_name $SUBDOMAIN;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_pass http://127.0.0.1:$port/;
    }
}
EOF
done < "$PROJECTS_FILE"

mv "$TMP_CONF" "$OUT_CONF"
chmod 0644 "$OUT_CONF"

# ==============================================================================
# 2. Generate Dynamic Dashboard
# ==============================================================================
echo "📄 Generating dashboard HTML..."
DASHBOARD_TMP="$(mktemp)"

cat > "$DASHBOARD_TMP" <<'HTMLHEAD'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VPS Projects Dashboard</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        font-family: system-ui, -apple-system, sans-serif;
        background: linear-gradient(135deg, #0f172a, #020617);
        color: #e2e8f0;
        padding: 20px;
      }
      h1 { text-align: center; margin-bottom: 10px; font-size: 2rem; }
      .domain-note {
        text-align: center; color: #94a3b8; margin-bottom: 30px;
        font-size: 0.95rem;
      }
      .container { max-width: 1000px; margin: auto; }
      .grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
        gap: 20px;
      }
      .card {
        background: #0f172a; border: 1px solid #1e293b; padding: 20px;
        border-radius: 12px; transition: 0.3s ease;
        position: relative; overflow: hidden;
      }
      .card:hover {
        transform: translateY(-5px); border-color: #38bdf8;
        box-shadow: 0 10px 25px rgba(56,189,248,0.15);
      }
      .card h2 { font-size: 1.1rem; margin-bottom: 8px; }
      .card .links {
        margin-top: 12px; display: flex; gap: 12px; flex-wrap: wrap;
      }
      .card a {
        display: inline-block; color: #38bdf8; text-decoration: none;
        font-weight: 500; font-size: 0.9rem; padding: 4px 10px;
        border: 1px solid #1e293b; border-radius: 6px; background: #020617;
      }
      .card a:hover { text-decoration: underline; border-color: #38bdf8; }
      .badge {
        font-size: 0.7rem; color: #64748b; display: block;
        margin-bottom: 4px; text-transform: uppercase; letter-spacing: 0.05em;
      }
      @media (max-width: 500px) {
        h1 { font-size: 1.5rem; }
        .card { padding: 16px; }
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>🚀 VPS Projects</h1>
      <div class="domain-note">
        Base domain: <strong>BASE_DOMAIN_PLACEHOLDER</strong>
        &nbsp;|&nbsp;
        Subdomains: <strong>{project}.BASE_DOMAIN_PLACEHOLDER</strong>
      </div>
      <div class="grid">
HTMLHEAD

# Inject actual base domain into the placeholder
sed -i "s/BASE_DOMAIN_PLACEHOLDER/$BASE_DOMAIN/g" "$DASHBOARD_TMP"

while IFS="|" read -r name path port; do
  name="${name#"${name%%[![:space:]]*}"}"
  name="${name%"${name##*[![:space:]]}"}"
  path="${path#"${path%%[![:space:]]*}"}"
  path="${path%"${path##*[![:space:]]}"}"
  port="${port#"${port%%[![:space:]]*}"}"
  port="${port%"${port##*[![:space:]]}"}"

  if [ -z "$name" ] || [[ "$name" == \#* ]]; then
    continue
  fi

  if [ -z "$path" ] || [ -z "$port" ]; then
    continue
  fi

  if [[ "$path" != /* ]]; then
    continue
  fi

  DISPLAY_NAME="$(echo "$name" | sed 's/-/ /g; s/.*/\u&/')"
  SUBDOMAIN="$name.$BASE_DOMAIN"

  cat >> "$DASHBOARD_TMP" <<EOF
        <div class="card">
          <span class="badge">$name</span>
          <h2>$DISPLAY_NAME</h2>
          <div class="links">
            <a target="_blank" href="$path">Path →</a>
            <a target="_blank" href="https://$SUBDOMAIN">Subdomain →</a>
          </div>
        </div>
EOF
done < "$PROJECTS_FILE"

cat >> "$DASHBOARD_TMP" <<'HTMLFOOT'
      </div>
    </div>
  </body>
</html>
HTMLFOOT

$SUDO cp "$DASHBOARD_TMP" "$WEB_ROOT/index.html"
rm -f "$DASHBOARD_TMP"

# ==============================================================================
# 3. Deploy Nginx Config
# ==============================================================================
echo "📄 Moving config to Nginx..."
$SUDO cp "$OUT_CONF" "$NGINX_CONF"

if [ -e "$NGINX_LINK" ] && [ ! -L "$NGINX_LINK" ]; then
  echo "🧹 Removing non-symlink: $NGINX_LINK"
  $SUDO rm -f "$NGINX_LINK"
fi
$SUDO ln -sf "$NGINX_CONF" "$NGINX_LINK"

echo "🧹 Disabling competing default servers on :80..."
if [ -d "$NGINX_DIR" ]; then
  $SUDO mkdir -p "$DISABLED_DIR/sites-enabled" "$DISABLED_DIR/conf.d"

  if [ -e "$NGINX_DEFAULT_LINK" ]; then
    $SUDO rm -f "$NGINX_DEFAULT_LINK" || true
  fi

  if [ -e "$NGINX_DEFAULT_CONF" ]; then
    $SUDO mv "$NGINX_DEFAULT_CONF" "$DISABLED_DIR/conf.d/$(basename "$NGINX_DEFAULT_CONF")" || true
  fi

  if [ -d "$SITES_ENABLED_DIR" ]; then
    for f in "$SITES_ENABLED_DIR"/*; do
      [ -e "$f" ] || continue
      base="$(basename "$f")"
      if [ "$base" = "$(basename "$NGINX_LINK")" ]; then
        continue
      fi
      if grep -Eq 'listen[[:space:]]+([[]::[]]:)?80[[:space:]]+default_server\b' "$f"; then
        echo "  - disabling $f"
        $SUDO mv "$f" "$DISABLED_DIR/sites-enabled/$base" || true
      fi
    done
  fi

  if [ -d "$CONF_D_DIR" ]; then
    for f in "$CONF_D_DIR"/*.conf; do
      [ -e "$f" ] || continue
      if grep -Eq 'listen[[:space:]]+([[]::[]]:)?80[[:space:]]+default_server\b' "$f"; then
        echo "  - disabling $f"
        $SUDO mv "$f" "$DISABLED_DIR/conf.d/$(basename "$f")" || true
      fi
    done
  fi
fi

echo "🔍 Testing Nginx config..."
$SUDO nginx -t || {
  echo "❌ nginx -t failed. Files that still contain default_server:"
  if [ -d "$NGINX_DIR" ]; then
    $SUDO rg -n "\\bdefault_server\\b" "$NGINX_DIR" -S || true
  fi
  exit 1
}

echo "♻️ Restarting Nginx..."
$SUDO systemctl restart nginx

# ==============================================================================
# 4. Certbot SSL
# ==============================================================================
if command -v certbot &> /dev/null; then
  echo "🔒 Certbot detected."

  if [ -z "$CERTBOT_EMAIL" ]; then
    echo ""
    echo "⚠️  To automatically obtain SSL certificates, set CERTBOT_EMAIL:"
    echo "     CERTBOT_EMAIL=your-email@example.com $0"
    echo ""
    echo "   Or run certbot manually:"
    CERTBOT_CMD="sudo certbot --nginx"
    for domain in "${DOMAINS[@]}"; do
      CERTBOT_CMD="$CERTBOT_CMD -d $domain"
    done
    echo "     $CERTBOT_CMD"
    echo ""
  else
    CERT_NAME="$BASE_DOMAIN"
    CERTBOT_ARGS="--nginx --non-interactive --agree-tos --email $CERTBOT_EMAIL --cert-name $CERT_NAME"
    for domain in "${DOMAINS[@]}"; do
      CERTBOT_ARGS="$CERTBOT_ARGS -d $domain"
    done

    if $SUDO certbot certificates 2>/dev/null | grep -q "Name: $CERT_NAME"; then
      echo "🔒 Re-installing existing certificate into Nginx..."
      $SUDO certbot $CERTBOT_ARGS --reinstall || {
        echo "⚠️  Certbot reinstall failed. You may need to run it manually."
      }
    else
      echo "🔒 Obtaining new SSL certificate for: ${DOMAINS[*]}"
      $SUDO certbot $CERTBOT_ARGS || {
        echo "⚠️  Certbot failed. Ensure DNS A records point to this server."
      }
    fi
  fi
else
  echo ""
  echo "ℹ️  Certbot not found. Install it to enable automatic SSL:"
  echo "     sudo apt update && sudo apt install certbot python3-certbot-nginx"
  echo ""
  echo "   Then run:"
  CERTBOT_CMD="sudo certbot --nginx"
  for domain in "${DOMAINS[@]}"; do
    CERTBOT_CMD="$CERTBOT_CMD -d $domain"
  done
  echo "     $CERTBOT_CMD"
  echo ""
fi

echo "✅ Nginx setup complete!"
echo ""
echo "📋 Access methods:"
echo "   • Path-based:  http://<server-ip>/<path>/"
echo "   • Subdomains:  https://<project>.$BASE_DOMAIN/"
echo "   • Dashboard:   https://$BASE_DOMAIN/"
